# Generated by Django 3.1.5 on 2021-01-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, choices=[('COMFORT', 'Удобный'), ('OPEN', 'Открытый')], max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categoryoffer')),
            ],
            options={
                'verbose_name': 'Offer Category',
                'verbose_name_plural': 'Offer Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, choices=[('GYM', 'Тренажерные Залы'), ('POOL', 'Бассейны'), ('YOGA', 'Студии Йоги')], max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categoryclub')),
            ],
            options={
                'verbose_name': 'Club Category',
                'verbose_name_plural': 'Club Categories',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True, choices=[('NEWS', 'Новинка'), ('DIET', 'Диета'), ('EXERCISE', 'Упражнение'), ('LIFE STYLE', 'Образ Жизни')], max_length=100)),
                ('title', models.CharField(max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
    ]
