# Generated by Django 3.1.5 on 2021-01-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='categorypost',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='category_logo'),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='name',
            field=models.SlugField(blank=True, choices=[('NEWS', 'Новинка'), ('DIET', 'Диета'), ('EXERCISE', 'Упражнение'), ('LIFE STYLE', 'Образ Жизни')], max_length=100),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categorypost'),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='categoryclub',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
