# Generated by Django 3.1.5 on 2021-02-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryclub',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='categorypost',
            old_name='name',
            new_name='slug',
        ),
    ]
