# Generated by Django 3.1.5 on 2021-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210126_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='name',
            field=models.SlugField(blank=True, choices=[('NEWS', 'Новинка'), ('DIET', 'Диета'), ('EXERCISE', 'Упражнение'), ('LIFE-STYLE', 'Образ Жизни')], max_length=100),
        ),
    ]
