# Generated by Django 3.1.5 on 2021-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210126_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclub',
            name='name',
            field=models.SlugField(blank=True, choices=[('gym', 'Fitness-Centers'), ('pool', 'Pools'), ('yoga', 'Yoga-Studios')], max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='name',
            field=models.SlugField(blank=True, choices=[('COMFORT', 'Comfort'), ('OPEN', 'Open')], max_length=100),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='name',
            field=models.SlugField(blank=True, choices=[('news', 'News'), ('diet', 'Diet'), ('exercises', 'Exercises'), ('life-style', 'Life-Style')], max_length=100),
        ),
    ]
