# Generated by Django 3.1.5 on 2021-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='area',
            field=models.IntegerField(max_length=4),
        ),
    ]
