# Generated by Django 3.1.5 on 2021-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210126_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='area',
            field=models.IntegerField(),
        ),
    ]
