# Generated by Django 3.1.5 on 2021-01-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1 MONTH', '1 месяц'), ('3 MONTHS', '3 месяца'), ('12 MONTHS', 'Круглый Год')], max_length=55)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField()),
                ('activation_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='category.categoryoffer')),
            ],
        ),
    ]
