# Generated by Django 3.1.5 on 2021-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20210126_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
